
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: curl -o- -L https://yarnpkg.com/install.sh | bash
  displayName: 'Install Yarn'

- script: yarn install
  displayName: 'Install dependencies'

- script: yarn add puppeteer
  displayName: 'Install puppeteer'

#- script: |
#    yarn test
#  displayName: 'yarn test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
